### ISSUE TITLE
Investigate Key Ring BE in Mainnet

### ISSUE THREAD

**Issue by GR3G0RYO** [planetmint/planetmint-go#150]

**Comment by jmastr** [comment]
That are our options:
```
The keyring supports the following backends:

    os          Uses the operating system's default credentials store.
    file        Uses encrypted file-based keystore within the app's configuration directory.
                This keyring will request a password each time it is accessed, which may occur
                multiple times in a single command resulting in repeated password prompts.
    kwallet     Uses KDE Wallet Manager as a credentials management application.
    pass        Uses the pass command line utility to store and retrieve keys.
    test        Stores keys insecurely to disk. It does not prompt for a password to be unlocked
                and it should be use only for testing purposes.
```

**Comment by jmastr** [comment]
Currently both, testnet and mainnet, are configured with `test` backend

**Comment by jmastr** [comment]
- `os` requests a password each time it is accessed and cannot be passed non-interactively
- `file` requests a password each time it is accessed and cannot be passed non-interactively
- `kwallet` does not apply to us
- `pass` backend depends on `pass` linux utility and requires GnuPG: https://gnupg.org/

**Comment by jmastr** [comment]
After talking to @eckelj, this is the outcome:
- The only suitable option at this point would be `pass` and encrypt the wallet with a PGP public key
- However then we need to have the PGP private key unprotected, thus only shifting the problem to another place
- We need an easily accessible wallet, because other than normal staking validators, our validators are automatically sending funds around

This is how bitcoin-cli and thus elements-cli do it:
- One sets a `passphrase` when creating the wallet
- One uses a dedicated `walletpassphrase` command to unlock the wallet for a certain amount of time
- One can interact normally with the unlocked wallet

This would be a nice behavior for the planetmint wallet too and could be implemented in the future.
