### ISSUE TITLE
Research validator election

### ISSUE THREAD

**Issue by eckelj** [planetmint/planetmint-go#99]
The Validator election is slightly different from the raw aspects of its integration in tendermint/cometBFT https://hub.cosmos.network/main/validators/validator-faq.html#becoming-a-validator and needs to be researched.

the following aspects have to be defined:
* requirements
* process
* final state

**Comment by eckelj** [comment]
Genesis: 2100000000 plmnt + 3 * 95000000 stake 
faucet was funded with plmnt
voting power was based on stake, not on plmnt. Thus, we could not give the new validator a stake without depositing from the other validators.

**Comment by jmastr** [comment]
The validator election is purely done by bonding a certain amount of voting power tokens (`stake`). We defined an amount of `1000000stake` to be necessary. 

Initially three validators were hardcoded into the genesis block and they were assigned 18000000stake in total, so that we can have 18 validators in the network.

how often a validator creates a block is weighted by the amount of stake he bonded. If everyone bonds the same amount of token a round-robin approach is achieved.
